version: "3"

services:
  db:
    image: "postgres:10-alpine"
    container_name: "postgres-prod"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: starter-prod
      POSTGRES_USER: starter-prod
      POSTGRES_PASSWORD: secret-prod
    env_file:
      - .env

  api:
    container_name: "api-prod"
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile.production
    env_file:
      - .env
    ports: 
      - "5000:5000" 
    depends_on:
      - db
    links:
      - db
    environment: 
      - APP_PORT:5000
      - NODE_ENV:production
      - DB_CLIENT:pg
      - DB_HOST:db
      - DB_PORT:5432
      - DB_NAME:starter-prod
      - DB_USER:starter-prod
      - DB_PASSWORD:secret-prod